//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileCopyBackup {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class FileCopyBaackup : global::System.Configuration.ApplicationSettingsBase {
        
        private static FileCopyBaackup defaultInstance = ((FileCopyBaackup)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FileCopyBaackup())));
        
        public static FileCopyBaackup Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"C:\\00.Dev\\temp\\SRC\"")]
        public string SRC_DIR {
            get {
                return ((string)(this["SRC_DIR"]));
            }
            set {
                this["SRC_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"C:\\00.Dev\\temp\\DEST\"")]
        public string DEST_DIR {
            get {
                return ((string)(this["DEST_DIR"]));
            }
            set {
                this["DEST_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"C:\\00.Dev\\temp\\LOG\"")]
        public string LOG_DIR {
            get {
                return ((string)(this["LOG_DIR"]));
            }
            set {
                this["LOG_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string DB_STR {
            get {
                return ((string)(this["DB_STR"]));
            }
            set {
                this["DB_STR"] = value;
            }
        }
    }
}
